pipeline {
    agent any

    environment {
        IMAGE_NAME = "nodejs-devops-mavericks"
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning repository...'
                // Jenkins will automatically clone if you connect repo, otherwise use checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh """
                    cd nodejsApp
                    docker build -t $IMAGE_NAME .
                """
            }
        }

        stage('Run Docker Container') {
            steps {
                echo 'Running Docker container...'
                sh """
                    docker rm -f nodejs-container || true
                    docker run -d -p 3000:3000 --name nodejs-container $IMAGE_NAME
                """
            }
        }

        stage('Test API') {
            steps {
                echo 'Testing /health endpoint...'
                sh 'sleep 5' // wait for container to start
                sh 'curl http://localhost:3000/health'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            // (optional) docker stop or remove
        }
    }
}
